name: ESLint

on:
  pull_request:
    types: [assigned, opened, reopened, synchronize, ready_for_review, review_requested, auto_merge_enabled]
  pull_request_review:
    types: [submitted]

permissions:
  pull-requests: write

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Install packages
        run: |
          npm install
          npm install @microsoft/eslint-formatter-sarif@2.1.7

      - name: Run ESLint
        run: npx eslint .
          --config .eslintrc.js
          --ext .js,.jsx,.ts,.tsx
          --format @microsoft/eslint-formatter-sarif
          --output-file eslint-results.sarif
        continue-on-error: true
        
      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@a56a03b370b87b26fde6d680755f818cfda0372b # v2.24.5
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true
