name: ESLint

on:
  pull_request:
    types: [assigned, opened, reopened, synchronize, ready_for_review, review_requested, auto_merge_enabled]
  pull_request_review:
    types: [submitted]

permissions:
  pull-requests: write

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install 
        run: npm install

      - name: Run ESLint
        run: npx eslint .
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true
